### ISSUE TITLE
python script gives errors

### ISSUE THREAD

**Issue by 8bit-meiko** [leots/Arduino-PC-Monitor#4]
the error i am getting is: Error: 'int' object is not subscriptable (line 129)

now i don't have any experience with python so i can't help with solving this sadly

this is in the main python file btw.

edit:
this is with newest installed python version on windows 8.1

**Comment by leots** [comment]
Hi,
this is the part of the code that gets the CPU core temperatures. How many cores are there in your system? Right now the program assumes there are exactly 4. 
If this is the problem, I will make a fix to show less temperatures in the 1st line.

**Comment by 8bit-meiko** [comment]
i am using an AMD a8-4500M which is exactly 4 cores.

i did notice i have one global cpu core sensor, not one per core

**Comment by 8bit-meiko** [comment]
got it to work now thanks to your little guidance :)

i had to comment out the cpu individual core temp, gpu ram and gpu fan. now it works like a sunshine

**Comment by leots** [comment]
Yeah, the problem was the one sensor. On my computer there is 4 separate ones... Glad to hear it's working 😃
